[build]
  command = "apt-get update && apt-get install -y default-libmysqlclient-dev && pip install -r requirements.txt"

[build.environment]
  MYSQLCLIENT_CFLAGS = "-I/usr/include/mysql"
  MYSQLCLIENT_LDFLAGS = "-L/usr/lib/mysql -lmysqlclient"

[build.environment]
  PYTHON_VERSION = "3.10"
